class Autogenerated {
  PageProps? pageProps;
  bool? bNSSP;

  Autogenerated({this.pageProps, this.bNSSP});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    pageProps = json['pageProps'] != null
        ? new PageProps.fromJson(json['pageProps'])
        : null;
    bNSSP = json['__N_SSP'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.pageProps != null) {
      data['pageProps'] = this.pageProps!.toJson();
    }
    data['__N_SSP'] = this.bNSSP;
    return data;
  }
}

class PageProps {
  List<Banners>? banners;
  List<Categories>? categories;
  Null? popups;
  String? sLang;
  Namespaces? nNamespaces;

  PageProps(
      {this.banners,
        this.categories,
        this.popups,
        this.sLang,
        this.nNamespaces});

  PageProps.fromJson(Map<String, dynamic> json) {
    if (json['banners'] != null) {
      banners = <Banners>[];
      json['banners'].forEach((v) {
        banners!.add(new Banners.fromJson(v));
      });
    }
    if (json['categories'] != null) {
      categories = <Categories>[];
      json['categories'].forEach((v) {
        categories!.add(new Categories.fromJson(v));
      });
    }
    popups = json['popups'];
    sLang = json['__lang'];
    nNamespaces = json['__namespaces'] != null
        ? new Namespaces.fromJson(json['__namespaces'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.banners != null) {
      data['banners'] = this.banners!.map((v) => v.toJson()).toList();
    }
    if (this.categories != null) {
      data['categories'] = this.categories!.map((v) => v.toJson()).toList();
    }
    data['popups'] = this.popups;
    data['__lang'] = this.sLang;
    if (this.nNamespaces != null) {
      data['__namespaces'] = this.nNamespaces!.toJson();
    }
    return data;
  }
}

class Banners {
  String? id;
  Title? title;
  String? position;
  String? image;
  String? url;
  bool? active;
  String? createdAt;
  String? updatedAt;
  String? shipperId;
  String? about;

  Banners(
      {this.id,
        this.title,
        this.position,
        this.image,
        this.url,
        this.active,
        this.createdAt,
        this.updatedAt,
        this.shipperId,
        this.about});

  Banners.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'] != null ? new Title.fromJson(json['title']) : null;
    position = json['position'];
    image = json['image'];
    url = json['url'];
    active = json['active'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    shipperId = json['shipper_id'];
    about = json['about'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    if (this.title != null) {
      data['title'] = this.title!.toJson();
    }
    data['position'] = this.position;
    data['image'] = this.image;
    data['url'] = this.url;
    data['active'] = this.active;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    data['shipper_id'] = this.shipperId;
    data['about'] = this.about;
    return data;
  }
}

class Title {
  String? uz;
  String? ru;
  String? en;

  Title({this.uz, this.ru, this.en});

  Title.fromJson(Map<String, dynamic> json) {
    uz = json['uz'];
    ru = json['ru'];
    en = json['en'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['uz'] = this.uz;
    data['ru'] = this.ru;
    data['en'] = this.en;
    return data;
  }
}

class Categories {
  String? id;
  String? slug;
  String? parentId;
  String? image;
  Title? description;
  Title? title;
  String? orderNo;
  bool? active;
  List<Products>? products;
  Null? childCategories;

  Categories(
      {this.id,
        this.slug,
        this.parentId,
        this.image,
        this.description,
        this.title,
        this.orderNo,
        this.active,
        this.products,
        this.childCategories});

  Categories.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    slug = json['slug'];
    parentId = json['parent_id'];
    image = json['image'];
    description = json['description'] != null
        ? new Title.fromJson(json['description'])
        : null;
    title = json['title'] != null ? new Title.fromJson(json['title']) : null;
    orderNo = json['order_no'];
    active = json['active'];
    if (json['products'] != null) {
      products = <Products>[];
      json['products'].forEach((v) {
        products!.add(new Products.fromJson(v));
      });
    }
    childCategories = json['child_categories'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['slug'] = this.slug;
    data['parent_id'] = this.parentId;
    data['image'] = this.image;
    if (this.description != null) {
      data['description'] = this.description!.toJson();
    }
    if (this.title != null) {
      data['title'] = this.title!.toJson();
    }
    data['order_no'] = this.orderNo;
    data['active'] = this.active;
    if (this.products != null) {
      data['products'] = this.products!.map((v) => v.toJson()).toList();
    }
    data['child_categories'] = this.childCategories;
    return data;
  }
}

class Products {
  String? id;
  int? outPrice;
  String? currency;
  String? string;
  String? type;
  List<String>? categories;
  String? brandId;
  String? rateId;
  String? image;
  bool? activeInMenu;
  bool? hasModifier;
  String? fromTime;
  String? toTime;
  bool? offAlways;
  Null? gallery;
  Title? title;
  Title? description;
  bool? active;
  String? iikoId;
  String? jowiId;

  Products(
      {this.id,
        this.outPrice,
        this.currency,
        this.string,
        this.type,
        this.categories,
        this.brandId,
        this.rateId,
        this.image,
        this.activeInMenu,
        this.hasModifier,
        this.fromTime,
        this.toTime,
        this.offAlways,
        this.gallery,
        this.title,
        this.description,
        this.active,
        this.iikoId,
        this.jowiId});

  Products.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    outPrice = json['out_price'];
    currency = json['currency'];
    string = json['string'];
    type = json['type'];
    categories = json['categories'].cast<String>();
    brandId = json['brand_id'];
    rateId = json['rate_id'];
    image = json['image'];
    activeInMenu = json['active_in_menu'];
    hasModifier = json['has_modifier'];
    fromTime = json['from_time'];
    toTime = json['to_time'];
    offAlways = json['off_always'];
    gallery = json['gallery'];
    title = json['title'] != null ? new Title.fromJson(json['title']) : null;
    description = json['description'] != null
        ? new Title.fromJson(json['description'])
        : null;
    active = json['active'];
    iikoId = json['iiko_id'];
    jowiId = json['jowi_id'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['out_price'] = this.outPrice;
    data['currency'] = this.currency;
    data['string'] = this.string;
    data['type'] = this.type;
    data['categories'] = this.categories;
    data['brand_id'] = this.brandId;
    data['rate_id'] = this.rateId;
    data['image'] = this.image;
    data['active_in_menu'] = this.activeInMenu;
    data['has_modifier'] = this.hasModifier;
    data['from_time'] = this.fromTime;
    data['to_time'] = this.toTime;
    data['off_always'] = this.offAlways;
    data['gallery'] = this.gallery;
    if (this.title != null) {
      data['title'] = this.title!.toJson();
    }
    if (this.description != null) {
      data['description'] = this.description!.toJson();
    }
    data['active'] = this.active;
    data['iiko_id'] = this.iikoId;
    data['jowi_id'] = this.jowiId;
    return data;
  }
}

class Namespaces {
  Common? common;

  Namespaces({this.common});

  Namespaces.fromJson(Map<String, dynamic> json) {
    common =
    json['common'] != null ? new Common.fromJson(json['common']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.common != null) {
      data['common'] = this.common!.toJson();
    }
    return data;
  }
}

class Common {
  String? home;
  String? blog;
  String? contacts;
  String? about;
  String? branches;
  String? menu;
  String? add;
  String? cart;
  String? logIn;
  String? signIn;
  String? personalData;
  String? profile;
  String? myOrders;
  String? logOut;
  String? sum;
  String? address;
  String? name;
  String? phoneNumber;
  String? openingHours;
  String? enterADeliveryAddress;
  String? singleCallCenter;
  String? contactText;
  String? allRightsReserved;
  String? signInWithYourPhoneNumber;
  String? sendCode;
  String? confirmationCode;
  String? sendAgain;
  String? confirm;
  String? wrongCodeEntered;
  String? wrongPhoneEntered;
  String? temporarilyUnavailable;
  String? changePhoneNumber;
  String? enterNewNumber;
  String? enterYourName;
  String? dateOfBirth;
  String? toCart;
  String? addToCart;
  String? added;
  String? addedToCart;
  String? orderSuccessText;
  String? goToMyOrders;
  String? successfully;
  String? orderNo;
  String? dateOfRegistration;
  String? change;
  String? save;
  String? myAddress;
  String? addAddress;
  String? addressName;
  String? floor;
  String? accommodation;
  String? building;
  String? apartment;
  String? addressDeleted;
  String? detailsChanged;
  String? nothingChanged;
  String? from;
  String? somethingElse;
  String? select;
  String? please;
  String? delivery;
  String? takeaway;
  String? deliveryAddress;
  String? searchByRestaurantName;
  String? selectTheTypeOfReception;
  String? theRestaurantWillCloseAt;
  String? restaurantWillCloseAt;
  String? restaurantWillOpenAt;
  String? worksAroundTheClock;
  String? toSeeYourCurrentMenu;
  String? takeawayOrder;
  String? or;
  String? cancel;
  String? lastName;
  String? signOut;
  String? changeData;
  String? unknown;
  String? telegramBot;

  Common(
      {this.home,
        this.blog,
        this.contacts,
        this.about,
        this.branches,
        this.menu,
        this.add,
        this.cart,
        this.logIn,
        this.signIn,
        this.personalData,
        this.profile,
        this.myOrders,
        this.logOut,
        this.sum,
        this.address,
        this.name,
        this.phoneNumber,
        this.openingHours,
        this.enterADeliveryAddress,
        this.singleCallCenter,
        this.contactText,
        this.allRightsReserved,
        this.signInWithYourPhoneNumber,
        this.sendCode,
        this.confirmationCode,
        this.sendAgain,
        this.confirm,
        this.wrongCodeEntered,
        this.wrongPhoneEntered,
        this.temporarilyUnavailable,
        this.changePhoneNumber,
        this.enterNewNumber,
        this.enterYourName,
        this.dateOfBirth,
        this.toCart,
        this.addToCart,
        this.added,
        this.addedToCart,
        this.orderSuccessText,
        this.goToMyOrders,
        this.successfully,
        this.orderNo,
        this.dateOfRegistration,
        this.change,
        this.save,
        this.myAddress,
        this.addAddress,
        this.addressName,
        this.floor,
        this.accommodation,
        this.building,
        this.apartment,
        this.addressDeleted,
        this.detailsChanged,
        this.nothingChanged,
        this.from,
        this.somethingElse,
        this.select,
        this.please,
        this.delivery,
        this.takeaway,
        this.deliveryAddress,
        this.searchByRestaurantName,
        this.selectTheTypeOfReception,
        this.theRestaurantWillCloseAt,
        this.restaurantWillCloseAt,
        this.restaurantWillOpenAt,
        this.worksAroundTheClock,
        this.toSeeYourCurrentMenu,
        this.takeawayOrder,
        this.or,
        this.cancel,
        this.lastName,
        this.signOut,
        this.changeData,
        this.unknown,
        this.telegramBot});

  Common.fromJson(Map<String, dynamic> json) {
    home = json['home'];
    blog = json['blog'];
    contacts = json['contacts'];
    about = json['about'];
    branches = json['branches'];
    menu = json['menu'];
    add = json['add'];
    cart = json['cart'];
    logIn = json['log_in'];
    signIn = json['sign_in'];
    personalData = json['personal_data'];
    profile = json['profile'];
    myOrders = json['my_orders'];
    logOut = json['log_out'];
    sum = json['sum'];
    address = json['address'];
    name = json['name'];
    phoneNumber = json['phone_number'];
    openingHours = json['opening_hours'];
    enterADeliveryAddress = json['enter_a_delivery_address'];
    singleCallCenter = json['single_call_center'];
    contactText = json['contact_text'];
    allRightsReserved = json['all_rights_reserved'];
    signInWithYourPhoneNumber = json['sign_in_with_your_phone_number'];
    sendCode = json['send_code'];
    confirmationCode = json['confirmation_code'];
    sendAgain = json['send_again'];
    confirm = json['confirm'];
    wrongCodeEntered = json['wrong_code_entered'];
    wrongPhoneEntered = json['wrong_phone_entered'];
    temporarilyUnavailable = json['temporarily_unavailable'];
    changePhoneNumber = json['change_phone_number'];
    enterNewNumber = json['enter_new_number'];
    enterYourName = json['enter_your_name'];
    dateOfBirth = json['date_of_birth'];
    toCart = json['to_cart'];
    addToCart = json['add_to_cart'];
    added = json['added'];
    addedToCart = json['added_to_cart'];
    orderSuccessText = json['order_success-text'];
    goToMyOrders = json['go_to_my_orders'];
    successfully = json['successfully'];
    orderNo = json['order_no'];
    dateOfRegistration = json['date_of_registration'];
    change = json['change'];
    save = json['save'];
    myAddress = json['my_address'];
    addAddress = json['add_address'];
    addressName = json['address_name'];
    floor = json['floor'];
    accommodation = json['accommodation'];
    building = json['building'];
    apartment = json['apartment'];
    addressDeleted = json['address_deleted'];
    detailsChanged = json['details_changed'];
    nothingChanged = json['nothing_changed'];
    from = json['from'];
    somethingElse = json['something_else?'];
    select = json['select'];
    please = json['please'];
    delivery = json['delivery'];
    takeaway = json['takeaway'];
    deliveryAddress = json['delivery_address'];
    searchByRestaurantName = json['search_by_restaurant_name'];
    selectTheTypeOfReception = json['select_the_type_of_reception'];
    theRestaurantWillCloseAt = json['The_restaurant_will_close_at'];
    restaurantWillCloseAt = json['restaurant_will_close_at'];
    restaurantWillOpenAt = json['restaurant_will_open_at'];
    worksAroundTheClock = json['works_around_the_clock'];
    toSeeYourCurrentMenu = json['to_see_your_current_menu'];
    takeawayOrder = json['takeaway_order'];
    or = json['or'];
    cancel = json['cancel'];
    lastName = json['last_name'];
    signOut = json['sign_out'];
    changeData = json['change_data'];
    unknown = json['unknown'];
    telegramBot = json['telegram_bot'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['home'] = this.home;
    data['blog'] = this.blog;
    data['contacts'] = this.contacts;
    data['about'] = this.about;
    data['branches'] = this.branches;
    data['menu'] = this.menu;
    data['add'] = this.add;
    data['cart'] = this.cart;
    data['log_in'] = this.logIn;
    data['sign_in'] = this.signIn;
    data['personal_data'] = this.personalData;
    data['profile'] = this.profile;
    data['my_orders'] = this.myOrders;
    data['log_out'] = this.logOut;
    data['sum'] = this.sum;
    data['address'] = this.address;
    data['name'] = this.name;
    data['phone_number'] = this.phoneNumber;
    data['opening_hours'] = this.openingHours;
    data['enter_a_delivery_address'] = this.enterADeliveryAddress;
    data['single_call_center'] = this.singleCallCenter;
    data['contact_text'] = this.contactText;
    data['all_rights_reserved'] = this.allRightsReserved;
    data['sign_in_with_your_phone_number'] = this.signInWithYourPhoneNumber;
    data['send_code'] = this.sendCode;
    data['confirmation_code'] = this.confirmationCode;
    data['send_again'] = this.sendAgain;
    data['confirm'] = this.confirm;
    data['wrong_code_entered'] = this.wrongCodeEntered;
    data['wrong_phone_entered'] = this.wrongPhoneEntered;
    data['temporarily_unavailable'] = this.temporarilyUnavailable;
    data['change_phone_number'] = this.changePhoneNumber;
    data['enter_new_number'] = this.enterNewNumber;
    data['enter_your_name'] = this.enterYourName;
    data['date_of_birth'] = this.dateOfBirth;
    data['to_cart'] = this.toCart;
    data['add_to_cart'] = this.addToCart;
    data['added'] = this.added;
    data['added_to_cart'] = this.addedToCart;
    data['order_success-text'] = this.orderSuccessText;
    data['go_to_my_orders'] = this.goToMyOrders;
    data['successfully'] = this.successfully;
    data['order_no'] = this.orderNo;
    data['date_of_registration'] = this.dateOfRegistration;
    data['change'] = this.change;
    data['save'] = this.save;
    data['my_address'] = this.myAddress;
    data['add_address'] = this.addAddress;
    data['address_name'] = this.addressName;
    data['floor'] = this.floor;
    data['accommodation'] = this.accommodation;
    data['building'] = this.building;
    data['apartment'] = this.apartment;
    data['address_deleted'] = this.addressDeleted;
    data['details_changed'] = this.detailsChanged;
    data['nothing_changed'] = this.nothingChanged;
    data['from'] = this.from;
    data['something_else?'] = this.somethingElse;
    data['select'] = this.select;
    data['please'] = this.please;
    data['delivery'] = this.delivery;
    data['takeaway'] = this.takeaway;
    data['delivery_address'] = this.deliveryAddress;
    data['search_by_restaurant_name'] = this.searchByRestaurantName;
    data['select_the_type_of_reception'] = this.selectTheTypeOfReception;
    data['The_restaurant_will_close_at'] = this.theRestaurantWillCloseAt;
    data['restaurant_will_close_at'] = this.restaurantWillCloseAt;
    data['restaurant_will_open_at'] = this.restaurantWillOpenAt;
    data['works_around_the_clock'] = this.worksAroundTheClock;
    data['to_see_your_current_menu'] = this.toSeeYourCurrentMenu;
    data['takeaway_order'] = this.takeawayOrder;
    data['or'] = this.or;
    data['cancel'] = this.cancel;
    data['last_name'] = this.lastName;
    data['sign_out'] = this.signOut;
    data['change_data'] = this.changeData;
    data['unknown'] = this.unknown;
    data['telegram_bot'] = this.telegramBot;
    return data;
  }
}